# Generated by Django 4.0.4 on 2022-05-21 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course', to_field='course_id'),
        ),
        migrations.AlterField(
            model_name='courseclassroom',
            name='Teacher_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.teacher', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='courseclassroom',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course', to_field='course_id', unique=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course', to_field='course_id'),
        ),
        migrations.AlterField(
            model_name='studentcourseclassroom',
            name='Student_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='studentcourseclassroom',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course', to_field='course_id'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='Student_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course', to_field='course_id'),
        ),
    ]
