# Generated by Django 4.0.4 on 2022-06-04 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_notice_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.courseclassroom', to_field='course_id'),
        ),
        migrations.AlterField(
            model_name='studentcourseclassroom',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.courseclassroom', to_field='course_id', unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.studentcourseclassroom', to_field='course_id'),
        ),
    ]
