# Generated by Django 4.0.4 on 2022-06-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_assignment_course_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='submission_portal',
            new_name='has_submission_portal',
        ),
    ]
