# Generated by Django 4.0.4 on 2022-06-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_rename_submission_portal_assignment_has_submission_portal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file_path',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
