# Generated by Django 4.0.4 on 2022-06-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_rename_file_path_assignment_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='file_path',
        ),
        migrations.AddField(
            model_name='submission',
            name='uploaded_file',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_file',
            field=models.FileField(default='None', null=True, upload_to=''),
        ),
    ]
